Models/EmprestimoModel.cs
using System.ComponentModel.DataAnnotations;

namespace Biblioteca.Models
{
    public class EmprestimoModel
    {
        public int Id {  get; set; }

		[Required(ErrorMessage = "Digite o campo do Recebedor")]
		public string Recebedor { get; set; }

		[Required(ErrorMessage = "Digite o campo do Fornecedor")]
		public string Fornecedor { get; set; }

		[Required(ErrorMessage = "Digite o nome do Livro")]
		public string LivroEmprestado { get; set; }
        public DateTime DataRecebedor { get; set; } = DateTime.Now; // Data atual
    }
}

Models/ErrorViewModel.cs
namespace Biblioteca.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/EmprestimoController.cs
using Biblioteca.Data;
using Biblioteca.Models;
using Microsoft.AspNetCore.Mvc;

namespace Biblioteca.Controllers
{
    public class EmprestimoController : Controller
    {
        readonly private ApplicationDbContext _db;

        public EmprestimoController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<EmprestimoModel> emprestimos = _db.Emprestimo;
            return View(emprestimos);
        }

        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar(EmprestimoModel emprestimo)
        {
            if (ModelState.IsValid)
            {
                _db.Emprestimo.Add(emprestimo);
                _db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpGet]
        public IActionResult Editar(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            EmprestimoModel emprestimo = _db.Emprestimo.FirstOrDefault(x => x.Id == id);

            if (emprestimo == null)
            {
                return NotFound();
            }

            return View(emprestimo);
        }

        [HttpPost]
        public IActionResult Editar(EmprestimoModel emprestimo)
        {
            if (ModelState.IsValid)
            {
                _db.Emprestimo.Update(emprestimo);
                _db.SaveChanges();

                return RedirectToAction("Index");

            }

            return View(emprestimo);
        }

        [HttpGet]
        public IActionResult Excluir(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            EmprestimoModel emprestimo = _db.Emprestimo.FirstOrDefault(x => x.Id == id);

            if (emprestimo == null)
            {
                return NotFound();
            }

            return View(emprestimo);
        }

		[HttpPost]
		public IActionResult Excluir(EmprestimoModel emprestimo)
		{
			if (emprestimo == null)
			{
                return NotFound();
			}

			_db.Emprestimo.Remove(emprestimo);
			_db.SaveChanges();

			return RedirectToAction("Index");
		}
	}
}

Controllers/HomeController.cs
using Biblioteca.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Biblioteca.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Emprestimo/Cadastrar.cshtml
@model EmprestimoModel
@{
	ViewData["title"] = "Cadastrar Empréstimo"; // Muda o título da página
}

<div class="container bg-dark p-5 rounded-5">
	<div class="mb-5 text-center">
		<h1 class="text-light">Cadastro de Empréstimo</h1>
	</div>

	<form method="post" asp-controller="Emprestimo" asp-action="Cadastrar">
		<div class="form-group">
			<label for="Recebedor" class="text-light">Endereço de email</label>
			<input type="text" class="form-control" id="Recebedor" asp-for="Recebedor" aria-describedby="emailHelp" placeholder="Quem recebe o livro?"/>
			<span class="text-danger" asp-validation-for="Recebedor"></span>
		</div>
		<div class="form-group">
			<label for="Fornecedor" class="text-light">Fornecedor</label>
			<input type="text" class="form-control" id="Fornecedor" asp-for="Fornecedor" placeholder="Quem empresta o livro?"/>
			<span class="text-danger" asp-validation-for="Fornecedor"></span>
		</div>
		<div class="form-group">
			<label for="Livro" class="text-light">Livro</label>
			<input type="text" class="form-control" id="Livro" asp-for="LivroEmprestado" placeholder="Qual o livro?"/>
			<span class="text-danger" asp-validation-for="LivroEmprestado"></span>
		</div>

		<div class="d-flex gap-5 mt-5">
			<button type="submit" class="btn btn-success w-50">Enviar</button>
			<a class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>
		</div>
	</form>
</div>

Views/Emprestimo/Editar.cshtml
@model EmprestimoModel
@{
	ViewData["title"] = "Editar Empréstimo"; // Muda o título da página
}

<div class="container bg-dark p-5 rounded-5">
	<div class="mb-5 text-center">
		<h1 class="text-light">Editar Empréstimo</h1>
	</div>

	<form method="post" asp-controller="Emprestimo" asp-action="Editar">
		<input type="hidden" asp-for="Id" />
		<div class="form-group">
			<label for="Recebedor" class="text-light">Endereço de email</label>
			<input type="text" class="form-control" id="Recebedor" asp-for="Recebedor" aria-describedby="emailHelp" placeholder="Quem recebe o livro?" />
			<span class="text-danger" asp-validation-for="Recebedor"></span>
		</div>
		<div class="form-group">
			<label for="Fornecedor" class="text-light">Fornecedor</label>
			<input type="text" class="form-control" id="Fornecedor" asp-for="Fornecedor" placeholder="Quem empresta o livro?" />
			<span class="text-danger" asp-validation-for="Fornecedor"></span>
		</div>
		<div class="form-group">
			<label for="Livro" class="text-light">Livro</label>
			<input type="text" class="form-control" id="Livro" asp-for="LivroEmprestado" placeholder="Qual o livro?" />
			<span class="text-danger" asp-validation-for="LivroEmprestado"></span>
		</div>

		<div class="d-flex gap-5 mt-5">
			<button type="submit" class="btn btn-success w-50">Enviar</button>
			<a class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>
		</div>
	</form>
</div>

Views/Emprestimo/Excluir.cshtml
@model EmprestimoModel
@{
	ViewData["title"] = "Excluir Empréstimo"; // Muda o título da página
}

<div class="container bg-dark p-5 rounded-5">
	<div class="mb-5 text-center">
		<h1 class="text-light">Excluir Empréstimo</h1>
	</div>

	<form method="post" asp-controller="Emprestimo" asp-action="Excluir">
		<input type="hidden" asp-for="Id" />

		<h2 class="text-light">Tem certeza que deseja excluir?</h2>

		<div class="form-group">
			<label for="Recebedor" class="text-light">Endereço de email</label>
			<input type="text" disabled class="form-control" id="Recebedor" asp-for="Recebedor" aria-describedby="emailHelp" placeholder="Quem recebe o livro?" />
			<span class="text-danger" asp-validation-for="Recebedor"></span>
		</div>
		<div class="form-group">
			<label for="Fornecedor" class="text-light">Fornecedor</label>
			<input type="text" disabled class="form-control" id="Fornecedor" asp-for="Fornecedor" placeholder="Quem empresta o livro?" />
			<span class="text-danger" asp-validation-for="Fornecedor"></span>
		</div>
		<div class="form-group">
			<label for="Livro" class="text-light">Livro</label>
			<input type="text" disabled class="form-control" id="Livro" asp-for="LivroEmprestado" placeholder="Qual o livro?" />
			<span class="text-danger" asp-validation-for="LivroEmprestado"></span>
		</div>

		<div class="d-flex gap-5 mt-5">
			<button type="submit" class="btn btn-success w-50">Excluir</button>
			<a class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>
		</div>
	</form>
</div>

Views/Emprestimo/Index.cshtml
@model IEnumerable<EmprestimoModel>

<div class="container">
    <div class="d-flex justify-content-between align-items-center mb-5">
        <h1>Empréstimos</h1>
        <a class="btn btn-success mx-2" asp-controller="Emprestimo" asp-action="Cadastrar">Cadastrar novo empréstimo</a>
    </div>

    <table class="table table-striped table-dark">
        <thead>
            <tr>
                <th scope="col">Recebedor</th>
                <th scope="col">Fornecedor</th>
                <th scope="col">Livro</th>
                <th scope="col">Data</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
                @if (Model != null)
                {
                    @foreach (var emprestimo in Model)
                    {
                            <tr>
                                <th scope="row">@emprestimo.Recebedor</th>
                                <td>@emprestimo.Fornecedor</td>
                                <td>@emprestimo.LivroEmprestado</td>
                                <td>@emprestimo.DataRecebedor</td>
                                <td>
                                    <a asp-controller="Emprestimo" asp-action="Editar" asp-route-id="@emprestimo.Id" class="btn btn-warning mx-2">Editar</a>
                            <a asp-controller="Emprestimo" asp-action="Excluir" asp-route-id="@emprestimo.Id" class="btn btn-danger mx-2">Excluir</a>
                                </td>
                            </tr>
                    }
                }
        </tbody>
    </table>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Biblioteca</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Biblioteca.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Biblioteca</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Emprestimo" asp-action="Index">Emprestimos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Biblioteca - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>